//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.09 at 02:58:08 PM MSK 
//


package by.bsu.orangery.entity;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CutFlower complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CutFlower">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.example.com/flowers}Flower">
 *       &lt;sequence>
 *         &lt;element name="price" type="{http://www.example.com/flowers}Price"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CutFlower", propOrder = {
    "price"
})
public class CutFlower
    extends Flower
{

    @XmlElement(required = true)
    protected BigInteger price;

    /**
     * Gets the value of the price property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPrice() {
        return price;
    }

    /**
     * Sets the value of the price property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPrice(BigInteger value) {
        this.price = value;
    }

    @Override
    public String toString() {
        return "\n-------------------\n" +
                "CutFlower{\n" +
                "ID=" + super.getId() + "\n" +
                "Name=" + super.getName() + "\n" +
                "Origin=" + super.getOrigin() + "\n" +
                "Stem Color=" + super.getVisualParameters().getStemColor() + "\n" +
                "Leaf Color=" + super.getVisualParameters().getLeafColor() + "\n" +
                "Plant Size=" + super.getVisualParameters().getPlantSize() + "\n" +
                "Price=" + price + "\n" +
                '}' +
                "\n-------------------\n";
    }
}
