//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.09 at 02:58:08 PM MSK 
//


package by.bsu.orangery.entity;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Visual complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Visual">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="stem-color" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="leaf-color" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="plant-size" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Visual", propOrder = {
    "stemColor",
    "leafColor",
    "plantSize"
})
public class Visual {

    @XmlElement(name = "stem-color", required = true)
    protected String stemColor;
    @XmlElement(name = "leaf-color", required = true)
    protected String leafColor;
    @XmlElement(name = "plant-size", required = true)
    protected BigInteger plantSize;

    /**
     * Gets the value of the stemColor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStemColor() {
        return stemColor;
    }

    /**
     * Sets the value of the stemColor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStemColor(String value) {
        this.stemColor = value;
    }

    /**
     * Gets the value of the leafColor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLeafColor() {
        return leafColor;
    }

    /**
     * Sets the value of the leafColor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLeafColor(String value) {
        this.leafColor = value;
    }

    /**
     * Gets the value of the plantSize property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPlantSize() {
        return plantSize;
    }

    /**
     * Sets the value of the plantSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPlantSize(BigInteger value) {
        this.plantSize = value;
    }

}
